ring1: add reboot-to-netboot systemd trigger in the butane file
Signed-off-by: Mathieu Grzybek <github@grzybek.fr>

diff --git a/ring1/kubernetes/capi-kamaji-vm-flatcar/system.yaml b/ring1/kubernetes/capi-kamaji-vm-flatcar/system.yaml
--- a/ring1/kubernetes/capi-kamaji-vm-flatcar/system.yaml
+++ b/ring1/kubernetes/capi-kamaji-vm-flatcar/system.yaml
@@ -6,6 +6,7 @@ kernel_arguments:
 storage:
   directories:
     - path: /etc/kubernetes/manifests
+    - path: /opt/sbin
   links:
     - target: /opt/extensions/kubernetes/kubernetes-v1.33.2-x86-64.raw
       path: /etc/extensions/kubernetes.raw
@@ -15,6 +16,24 @@ storage:
     - path: /etc/ssl/certs/microcloud.pem
       contents:
         local: bundle.crt
+    # Reboot to netboot
+    - path: /opt/sbin/reboot-to-netboot.sh
+      mode: 0755
+      contents:
+        inline: |
+          #!/bin/bash
+          # Get Network/PXE boot ID
+          BOOT_ID=$(efibootmgr | grep -Ei "http|network|pxe" | head -n 1 | awk '{gsub("Boot","");print $1}')
+          if [ -z "$BOOT_ID" ]; then
+              echo "Error : no boot ID found"
+              exit 1
+          fi
+
+          echo "Configuring next boot to: $BOOT_ID"
+          efibootmgr --bootnext "$BOOT_ID"
+
+          rm -f /var/run/reboot-to-netboot-required
+          reboot
     # kubernetes
     - path: /etc/sysupdate.kubernetes.d/kubernetes-v1.33.conf
       contents:
@@ -82,6 +101,24 @@ systemd:
       enabled: true
     - name: locksmithd.service
       mask: true
+    ###########################################################################
+    # Reboot to netboot
+    - name: reboot-to-netboot.path
+      enabled: true
+      contents: |
+        [Unit]
+        Description=Watches the designated file to trigger a netboot
+        [Path]
+        PathExists=/var/run/reboot-to-netboot-required
+        [Install]
+        WantedBy=multi-user.target
+    - name: reboot-to-netboot.service
+      contents: |
+        [Unit]
+        Description=Starts the reboot on the netboot target
+        [Service]
+        Type=simple
+        ExecStart=/opt/sbin/reboot-to-netboot.sh
     ###########################################################################
     # Kubernetes
     - name: systemd-sysupdate.service
